apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meudeployment
  template:
    metadata:
      labels:
        app: meudeployment
    spec:
      containers:
        - name: web
          image: rafaelsallesdev/conversao-temperatura:v1
          ports:
          - containerPort: 8080