apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meudeployment
  template:
    metadata:
      labels:
        app: meudeployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Imagem oficial do NGINX
          ports:
            - containerPort: 80  # Porta interna do contêiner usada pelo NGINX
