apiVersion: v1
kind: Service
metadata:
  name: web-page-service
spec:
  selector:
    app: meudeployment
  ports:
    - protocol: TCP
      port: 8080        # Porta externa
      targetPort: 80    # Porta interna usada pelo contêiner
  type: NodePort
