apiVersion: v1
kind: Service
metadata:
  name: web-page-service
spec:
  selector:
    app: meudeployment
  ports:
    - protocol: TCP
      port: 8081        # Porta externa usada para acessar o NGINX
      targetPort: 80    # Porta interna do contêiner
  type: NodePort
